### ISSUE TITLE
another "xml2" install error in centos 6

### ISSUE THREAD

**Issue by wdkrnls** [r-lib/xml2#173]
### xml2 fails to install

I am using:

```
R version 3.3.3 (2017-03-06)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS release 6.6 (Final)
```

Whether I run `install.packages("xml2")` or `devtools::install_github("hadley/xml2")` I get the same error below:

```
** package 'xml2' successfully unpacked and MD5 sums checked
Found pkg-config cflags and libs!
Using PKG_CFLAGS=-I/opt/rocks/include/libxml2
Using PKG_LIBS=-L/opt/rocks/lib -lxml2 -lz -lm
** libs
g++ -I/share/apps/R/R-3.3.3-openblas/lib64/R/include -DNDEBUG -I../inst/include -I/opt/rocks/include/libxml2 -I/usr/local/include -I"/home/wdkrnls/R/lib/6/3.3/Rcpp/include" -I"/home/wdkrnls/R/lib/6/3.3/BH/include"   -fpic  -g -O2  -c RcppExports.cpp -o RcppExports.o
g++ -I/share/apps/R/R-3.3.3-openblas/lib64/R/include -DNDEBUG -I../inst/include -I/opt/rocks/include/libxml2 -I/usr/local/include -I"/home/wdkrnls/R/lib/6/3.3/Rcpp/include" -I"/home/wdkrnls/R/lib/6/3.3/BH/include"   -fpic  -g -O2  -c connection.cpp -o connection.o
g++ -I/share/apps/R/R-3.3.3-openblas/lib64/R/include -DNDEBUG -I../inst/include -I/opt/rocks/include/libxml2 -I/usr/local/include -I"/home/wdkrnls/R/lib/6/3.3/Rcpp/include" -I"/home/wdkrnls/R/lib/6/3.3/BH/include"   -fpic  -g -O2  -c xml2_doc.cpp -o xml2_doc.o
xml2_doc.cpp: In function 'Rcpp::IntegerVector xml_parse_options()':
xml2_doc.cpp:82: error: 'XML_PARSE_OLD10' was not declared in this scope
xml2_doc.cpp:83: error: 'XML_PARSE_NOBASEFIX' was not declared in this scope
xml2_doc.cpp:84: error: 'XML_PARSE_HUGE' was not declared in this scope
xml2_doc.cpp:85: error: 'XML_PARSE_OLDSAX' was not declared in this scope
make: *** [xml2_doc.o] Error 1
ERROR: compilation failed for package 'xml2'
```
-->

<details>
<summary>Session Info</summary>

```r
devtools::session_info() # Paste output below
#> output
> sessionInfo()
R version 3.3.3 (2017-03-06)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS release 6.6 (Final)

locale:
 [1] LC_CTYPE=en_US.iso885915       LC_NUMERIC=C                  
 [3] LC_TIME=en_US.iso885915        LC_COLLATE=en_US.iso885915    
 [5] LC_MONETARY=en_US.iso885915    LC_MESSAGES=en_US.iso885915   
 [7] LC_PAPER=en_US.iso885915       LC_NAME=C                     
 [9] LC_ADDRESS=C                   LC_TELEPHONE=C                
[11] LC_MEASUREMENT=en_US.iso885915 LC_IDENTIFICATION=C           

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] devtools_1.12.0

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.10   digest_0.6.12  dplyr_0.5.0    withr_1.0.2    assertthat_0.1
 [6] R6_2.2.0       DBI_0.6        git2r_0.18.0   magrittr_1.5   httr_1.2.1    
[11] curl_2.4       tools_3.3.3    compiler_3.3.3 memoise_1.0.0  knitr_1.15.1  
[16] tibble_1.2    
```
</details>

Maybe this is due to older libxml2?

```
xmllint --version
xmllint: using libxml version 20706
```

**Comment by zhenyisong** [comment]
@wdkrnls Did you solve the issue? I met the same problem.

**Comment by jimhester** [comment]
Yes this is due to an older xml2, should now be fixed.

**Comment by RamasamyKandasamy** [comment]
Dear jimhester, I guess this is not yet fixed. I am having the same problem. 

`> install.packages("xml2")
Installing package into ‘/home/ramasamy/R/x86_64-pc-linux-gnu-library/3.4’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/src/contrib/xml2_1.2.0.tar.gz'
Content type 'application/x-gzip' length 251614 bytes (245 KB)
==================================================
downloaded 245 KB

* installing *source* package ‘xml2’ ...
** package ‘xml2’ successfully unpacked and MD5 sums checked
Found pkg-config cflags and libs!
Using PKG_CFLAGS=-I/usr/local/include/libxml2
Using PKG_LIBS=-L/usr/local/lib -lxml2 -lz -lm
** libs
g++  -I/usr/share/R/include -DNDEBUG -I../inst/include -I/usr/local/include/libxml2 -I"/home/ramasamy/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include"   -fvisibility=hidden -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c RcppExports.cpp -o RcppExports.o
g++  -I/usr/share/R/include -DNDEBUG -I../inst/include -I/usr/local/include/libxml2 -I"/home/ramasamy/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include"   -fvisibility=hidden -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c connection.cpp -o connection.o
g++  -I/usr/share/R/include -DNDEBUG -I../inst/include -I/usr/local/include/libxml2 -I"/home/ramasamy/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include"   -fvisibility=hidden -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c xml2_doc.cpp -o xml2_doc.o
xml2_doc.cpp: In function ‘Rcpp::IntegerVector xml_parse_options()’:
xml2_doc.cpp:107:5: error: ‘XML_PARSE_OLDSAX’ was not declared in this scope
     XML_PARSE_OLDSAX,
     ^
/usr/lib/R/etc/Makeconf:168: recipe for target 'xml2_doc.o' failed
make: *** [xml2_doc.o] Error 1
ERROR: compilation failed for package ‘xml2’
* removing ‘/home/ramasamy/R/x86_64-pc-linux-gnu-library/3.4/xml2’
Warning in install.packages :
  installation of package ‘xml2’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/RtmpD3Qshc/downloaded_packages’`

I get the same error when I run `devtools::install_github("r-lib/xml2")`
`> devtools::install_github("r-lib/xml2")
Downloading GitHub repo r-lib/xml2@master
from URL https://api.github.com/repos/r-lib/xml2/zipball/master
Installing xml2
'/usr/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/tmp/RtmpD3Qshc/devtools20085aa465d3/r-lib-xml2-bb6efb2' --library='/home/ramasamy/R/x86_64-pc-linux-gnu-library/3.4'  \
  --install-tests 

* installing *source* package ‘xml2’ ...
Found pkg-config cflags and libs!
Using PKG_CFLAGS=-I/usr/local/include/libxml2
Using PKG_LIBS=-L/usr/local/lib -lxml2 -lz -lm
** libs
g++  -I/usr/share/R/include -DNDEBUG -I../inst/include -I/usr/local/include/libxml2 -I"/home/ramasamy/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include"   -fvisibility=hidden -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c RcppExports.cpp -o RcppExports.o
g++  -I/usr/share/R/include -DNDEBUG -I../inst/include -I/usr/local/include/libxml2 -I"/home/ramasamy/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include"   -fvisibility=hidden -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c connection.cpp -o connection.o
g++  -I/usr/share/R/include -DNDEBUG -I../inst/include -I/usr/local/include/libxml2 -I"/home/ramasamy/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include"   -fvisibility=hidden -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c xml2_doc.cpp -o xml2_doc.o
xml2_doc.cpp: In function ‘Rcpp::IntegerVector xml_parse_options()’:
xml2_doc.cpp:107:5: error: ‘XML_PARSE_OLDSAX’ was not declared in this scope
     XML_PARSE_OLDSAX,
     ^
/usr/lib/R/etc/Makeconf:168: recipe for target 'xml2_doc.o' failed
make: *** [xml2_doc.o] Error 1
ERROR: compilation failed for package ‘xml2’
* removing ‘/home/ramasamy/R/x86_64-pc-linux-gnu-library/3.4/xml2’
Installation failed: Command failed (1)`

I am using ubuntu 16.04 LTS.

`xmllint --version
xmllint: using libxml version 20907
   compiled with: Threads Tree Output Push Reader Patterns Writer SAXv1 FTP HTTP DTDValid HTML Legacy C14N Catalog XPath XPointer XInclude Iconv ICU ISO8859X Unicode Regexps Automata Expr Schemas Schematron Modules Debug Zlib Lzma `

Thank you!

**Comment by jimhester** [comment]
@RamasamyKandasamy that is strange, what is the output of

`grep DOTTED_VERSION /usr/local/include/libxml2/libxml/xmlversion.h`
and
`grep grep XML_PARSE_ /usr/local/include/libxml2/libxml/parser.h`

**Comment by RamasamyKandasamy** [comment]
The outputs are as follows:

```
$ grep DOTTED_VERSION /usr/local/include/libxml2/libxml/xmlversion.h
 * LIBXML_DOTTED_VERSION:
#define LIBXML_DOTTED_VERSION "2.7.2"
```

and 
```
~$ grep XML_PARSE_ /usr/local/include/libxml2/libxml/parser.h
    XML_PARSE_UNKNOWN = 0,
    XML_PARSE_DOM = 1,
    XML_PARSE_SAX = 2,
    XML_PARSE_PUSH_DOM = 3,
    XML_PARSE_PUSH_SAX = 4,
    XML_PARSE_READER = 5
    XML_PARSE_RECOVER	= 1<<0,	/* recover on errors */
    XML_PARSE_NOENT	= 1<<1,	/* substitute entities */
    XML_PARSE_DTDLOAD	= 1<<2,	/* load the external subset */
    XML_PARSE_DTDATTR	= 1<<3,	/* default DTD attributes */
    XML_PARSE_DTDVALID	= 1<<4,	/* validate with the DTD */
    XML_PARSE_NOERROR	= 1<<5,	/* suppress error reports */
    XML_PARSE_NOWARNING	= 1<<6,	/* suppress warning reports */
    XML_PARSE_PEDANTIC	= 1<<7,	/* pedantic error reporting */
    XML_PARSE_NOBLANKS	= 1<<8,	/* remove blank nodes */
    XML_PARSE_SAX1	= 1<<9,	/* use the SAX1 interface internally */
    XML_PARSE_XINCLUDE	= 1<<10,/* Implement XInclude substitition  */
    XML_PARSE_NONET	= 1<<11,/* Forbid network access */
    XML_PARSE_NODICT	= 1<<12,/* Do not reuse the context dictionnary */
    XML_PARSE_NSCLEAN	= 1<<13,/* remove redundant namespaces declarations */
    XML_PARSE_NOCDATA	= 1<<14,/* merge CDATA as text nodes */
    XML_PARSE_NOXINCNODE= 1<<15,/* do not generate XINCLUDE START/END nodes */
    XML_PARSE_COMPACT   = 1<<16,/* compact small text nodes; no modification of
    XML_PARSE_OLD10	= 1<<17,/* parse using XML-1.0 before update 5 */
    XML_PARSE_NOBASEFIX = 1<<18,/* do not fixup XINCLUDE xml:base uris */
    XML_PARSE_HUGE      = 1<<19 /* relax any hardcoded limit from the parser */
```

**Comment by jimhester** [comment]
Ah, so it looks like you have xml2 2.7.2 installed in that location and this `XML_PARSE_OLDSAX ` option was added in xml2 2.7.4. So my header guard is not right (it looks for xml2 >= 2.7.0).

Not really sure why you have this old version in `/usr/local`, but you will probably want to install the [libxml2-dev](https://packages.ubuntu.com/search?keywords=libxml2-dev) package which will install 2.9.3 and make sure your pkgconfig points to that version.
